apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vscode-workspace-pvc-rogue1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: vscode-workspace-pv-rogue1
  resources:
    requests:
      storage: 50Gi
