kind: Service
apiVersion: v1
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  selector:
    app: sqlserver
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
    name: http
  type: LoadBalancer
