apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc-dbhot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: mssql-pv-dbhot
  resources:
    requests:
      storage: 100Gi
