apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc-dbhot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: neo4j-pv-dbhot
  resources:
    requests:
      storage: 50Gi
