apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-dbhot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: mongo-pv-dbhot
  resources:
    requests:
      storage: 10Gi
