apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce 
  volumeName: mongo-pv
  resources:
    requests:
      storage: 3Gi