apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce 
  volumeName: mongo-pv
  resources:
    requests:
      storage: 3Gi