apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=          # base64 of 'postgres'
  POSTGRES_USER: YWRtaW4=            # base64 of 'admin'
  POSTGRES_PASSWORD: c2VjdXJlcGFzcw==  # base64 of 'securepass'