apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  selector:
    app: chatbot
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
      targetPort: 5000
  type: LoadBalancer
