apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: k8sdash
  namespace: kube-system 
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dashboard.kevin.local`)
      priority: 10
      services:
        - name: kubernetes-dashboard
          port: 443

