apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-dbhot
  labels:
    type: local
spec:
  storageClassName: manual-dbhot
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/dbhot/mysql"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: db-node
          operator: In
          values:
          - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-dbhot
spec:
  storageClassName: manual-dbhot
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
