apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: minecraft
  ports:
    - protocol: UDP
      port: 19132
      targetPort: 19132
