expose:
  type: loadBalancer
  tls:
    enabled: false
  loadBalancer:
    name: harbor

externalURL: http://harbor.kevin.local

internalTLS:
  enabled: false

harborAdminPassword: "Harbor12345"

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      existingClaim: harbor-registry-pvc
    database:
      existingClaim: harbor-database-pvc
    redis:
      existingClaim: harbor-redis-pvc
    jobservice:
      jobLog:
        existingClaim: harbor-jobservice
    trivy:
      existingClaim: ""
      storageClass: local-storage
      size: 5Gi

core:
  nodeSelector:
    db-node: "true"
  tolerations:
  - key: "db-only"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

jobservice:
  nodeSelector:
    db-node: "true"
  tolerations:
  - key: "db-only"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

nginx:
  nodeSelector:
    db-node: "true"
  tolerations:
  - key: "db-only"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

portal:
  nodeSelector:
    db-node: "true"
  tolerations:
  - key: "db-only"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

# Pin stateful components to the db-node
database:
  internal:
    nodeSelector:
      db-node: "true"
    tolerations:
    - key: "db-only"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

redis:
  internal:
    nodeSelector:
      db-node: "true"
    tolerations:
    - key: "db-only"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

registry:
  nodeSelector:
    db-node: "true"
  tolerations:
  - key: "db-only"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

trivy:
  enabled: false

metrics:
  enabled: false
