apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      nodeSelector:
        kubernetes.io/hostname: kevin-ubuntu
      containers:
      - name: vllm
        image: vllm/vllm/vllm-openai:latest-cuda12
        args:
          - "--model=bigcode/starcoder2-7b"
          - "--host=0.0.0.0"
          - "--tensor-parallel-size=1"
        ports:
          - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 1
        env:
          - name: HF_HOME
            value: /root/.cache/huggingface
        volumeMounts:
          - name: hf-cache
            mountPath: /root/.cache/huggingface
      volumes:
        - name: hf-cache
          emptyDir: {}