apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      nodeSelector:
        kubernetes.io/hostname: kevin-ubuntu
      containers:
      - name: ollama
        image: ollama/ollama:latest
        env:
        - name: num_ctx
          value: "8192"
        ports:
          - containerPort: 11434
        resources:
          requests:
            cpu: "4"
            memory: "16Gi"
          limits:
            cpu: "4"
            memory: "16Gi"
            nvidia.com/gpu: 2
        env:
          # Expose both GPUs to the container runtime layer
          - name: NVIDIA_VISIBLE_DEVICES
            value: "all"
          # Swap the indices: This forces Ollama to load and process on the 5060 Ti first
          - name: CUDA_VISIBLE_DEVICES
            value: "1,0"
        volumeMounts:
          - name: models
            mountPath: /root/.ollama
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: localai-models-pvc
