apiVersion: apps/v1
kind: Deployment
metadata:
  name: codescene-deployment
  labels:
    app: codescene
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codescene
  template:
    metadata:
      labels:
        app: codescene
    spec:
      containers:
      - name: codescene-container
        image: codescene/codescene:7.2.0
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres_password
        - name: DATABASE_URL
          value: "jdbc:postgresql://10.152.183.44:5432/postgres?user=$(POSTGRES_USER)&password=$(POSTGRES_PASSWORD)"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: codescene-data
          mountPath: /codescene/data
      volumes:
      - name: codescene-data
        persistentVolumeClaim:
          claimName: codescene-pvc