apiVersion: v1
kind: PersistentVolume
metadata:
  name: codescene-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/codescene
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codescene-pvc
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 10Gi