name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the frontend Docker image
      run: |
        docker login --username dornellaskj@gmail.com --password ${{ secrets.GH_password }} ghcr.io
        docker build . --file frontend/Dockerfile --tag ghcr.io/globofrontend:latest
        docker build . --file ordering/Dockerfile --tag ghcr.io/globoordering:latest
        docker build . --file catalog/Dockerfile --tag ghcr.io/globocatalog:latest
        docker push ghcr.io/globofrontend:latest
        docker push ghcr.io/globoordering:latest
        docker push ghcr.io/globocatalog:latest
