name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push frontend
      run: |
        docker login --username dornellaskj@gmail.com --password ${{ secrets.GH_password }} ghcr.io
        docker build . --file frontend/Dockerfile --tag ghcr.io/dornellaskj/globofrontend:latest
        docker push ghcr.io/dornellaskj/globofrontend:latest
    - name: Build and push ordering
      run: |
        docker login --username dornellaskj@gmail.com --password ${{ secrets.GH_password }} ghcr.io
        docker build . --file ordering/Dockerfile --tag ghcr.io/dornellaskj/globoordering:latest
        docker push ghcr.io/dornellaskj/globoordering:latest
    - name: Build and push catalog
      run: |
        docker login --username dornellaskj@gmail.com --password ${{ secrets.GH_password }} ghcr.io
        docker build . --file catalog/Dockerfile --tag ghcr.io/dornellaskj/globocatalog:latest
        docker push ghcr.io/dornellaskj/globocatalog:latest
